# Generated by Django 5.2 on 2025-04-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="tabs",
        ),
        migrations.AddField(
            model_name="track",
            name="tags",
            field=models.TextField(blank=True, help_text="Comma separated tags"),
        ),
    ]
