# Generated by Django 5.2 on 2025-04-13 03:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_track_tabs_track_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="audio_file",
            field=models.FileField(
                max_length=255, upload_to=api.models.track_upload_path
            ),
        ),
    ]
