# Generated by Django 5.2 on 2025-04-13 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_track_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="track",
            old_name="user",
            new_name="artist",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="website",
        ),
        migrations.RemoveField(
            model_name="track",
            name="tags",
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.TextField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="track",
            name="audio_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="track",
            name="audio_waveform_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="audio_waveform_resolution",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="track",
            name="title_slug",
            field=models.SlugField(default="test", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="track",
            name="title",
            field=models.CharField(max_length=125),
        ),
    ]
