# Generated by Django 5.2 on 2025-04-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_track_user_rename_user_track_artist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="title_slug",
            field=models.SlugField(max_length=255),
        ),
    ]
