# Generated by Django 5.2 on 2025-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_track_title_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
