# Generated by Django 5.2 on 2025-04-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_profile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
