# Generated by Django 5.2 on 2025-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_favoritetrack_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="audio_file",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
