# Generated by Django 5.2 on 2025-05-06 15:42

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_track_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Lowercase letters and numbers only.",
                max_length=150,
                unique=True,
                validators=[api.validators.AlphanumericUsernameValidator()],
            ),
        ),
    ]
