version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-demooo_db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "6543:5432" # can switch to 6543:5432 for local docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
    volumes:
      - ./backend:/app/backend
      - ./backend/.env.docker:/app/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      - ENVIRONMENT=docker
      - POSTGRES_HOST=db
    command: >
      sh -c "cd /app/backend && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: